<?php function stackCommerceGeneralSettingsPage()
{
    global $stackCommerceWidget_general_settings;
    ?>

    <form action="options.php" method="post">
        <?php
        settings_fields('stackCommerceWidget_general_settings');            // Retrieve the fields created for plugin options
        do_settings_sections('stackCommerce_general_page');                // Display the section(s) for the options page
        ?>
        <div>
            <?php
            submit_button();                                    // Form submit button generated by WordPress
            ?>
        </div>
    </form>
<?php }

function stackCommerce_general_callback()
{
    echo '<p>These options are global for all views </p>';
    if (isset($_GET['settings-updated'])) : ?>
        <div id="message" class="updated stackSocialMessage">
            <p><strong><?php _e('Settings saved.'); ?></strong></p>
        </div>
    <?php endif;

} // stackCommerceWidget_add_menu_item()


function stackCommerce_generalSection_callback()
{

    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve plugin options from the database

    echo '<input id="publisherID" name="stackCommerceWidget_general_options[publisherID]" type="text" value="' . $stackCommerce_general_options['publisherID'] . '">'; // Print the input field to the screen
} // stackCommerce_shortcodeSection_callback()

function stackCommerce_general_section_affiliate_callback()
{

    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve plugin options from the database
    echo '<input id="affiliateID" name="stackCommerceWidget_general_options[affiliateID]" type="text" value="' . $stackCommerce_general_options['affiliateID'] . '">'; // Print the input field to the screen
    echo '<div class="fieldDescription">This field applies to affiliate partners only. Please contact your StackCommerce account manager for questions or help identifying your affiliate ID.</div>';
} // stackCommerce_shortcodeSection_callback()

function stackCommerce_general_section_utm_source_callback()
{

    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve plugin options from the database

    echo '<input id="utmSourceInput" name="stackCommerceWidget_general_options[utm_source]" placeholder="utm_source, e.g. example.com" type="text" value="' . $stackCommerce_general_options['utm_source'] . '">'; // Print the input field to the screen
} // stackCommerce_shortcodeSection_callback()


function stackCommerce_general_section_additional_url_params_callback()
{

    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve plugin options from the database

    echo '<input id="additionalURLParams" name="stackCommerceWidget_general_options[additional_url_params]" placeholder="e.g. foo=bar&baz=qux" type="text" value="' . $stackCommerce_general_options['additional_url_params'] . '">'; // Print the input field to the screen
} // stackCommerce_shortcodeSection_callback()

function stackCommerce_general_validate($input)
{
    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve existing options values from the database

    /* Directly set values that don't require validation */
    $stackCommerce_general_options['publisherID'] = $input['publisherID'];
    $stackCommerce_general_options['utm_source'] = $input['utm_source'];
    $stackCommerce_general_options['additional_url_params'] = $input['additional_url_params'];
    $stackCommerce_general_options['affiliateID'] = $input['affiliateID'];

    if ($input['open_new_tab'] == NULL) {
        $stackCommerce_general_options['open_new_tab'] = "off";
    } else {
        $stackCommerce_general_options['open_new_tab'] = "on";
    }


    return $stackCommerce_general_options; // Send values to database
} // stackCommerce_shortcode_validate()


function stackCommerce_general_section_open_new_tab_callback()
{


    $stackCommerce_general_options = get_option('stackCommerceWidget_general_options'); // Retrieve plugin options from the database
    if ($stackCommerce_general_options['open_new_tab'] == NULL) {
        $stackCommerce_general_options['open_new_tab'] = "on";
    }
    /* Determine whether the box should be checked based on setting in database */
    if ($stackCommerce_general_options['open_new_tab'] == "on") {
        $checked = 'checked';
    } else {
        $checked = '';
    }
    echo '<input id="openNewTab" name="stackCommerceWidget_general_options[open_new_tab]" type="checkbox" ' . $checked . '>'; // Print the input field to the screen
}

?>